project_name: container-tag-exists
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w
  - -X github.com/Hsn723/container-tag-exists/cmd.version={{.Version}}
  - -X github.com/Hsn723/container-tag-exists/cmd.commit={{.Commit}}
  - -X github.com/Hsn723/container-tag-exists/cmd.date={{.Date}}
  - -X github.com/Hsn723/container-tag-exists/cmd.builtBy=goreleaser
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-dev"
changelog:
  use: github-native
source:
  enabled: true
sboms:
- id: archive
  artifacts: archive
- id: source
  artifacts: source
signs:
- cmd: cosign
  certificate: "${artifact}.pem"
  args:
  - sign-blob
  - "--yes"
  - "--output-certificate=${certificate}"
  - "--output-signature=${signature}"
  - "${artifact}"
  artifacts: all
  output: true
